on:
  push:
  pull_request:

jobs:
  test:
    name: Test on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - name: get latest build tools
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa -y
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -y gperf help2man libtool-bin gcc-11 g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
        sudo update-alternatives --install /usr/bin/cpp cpp-bin /usr/bin/cpp-11 100
        wget https://ftp.gnu.org/gnu/make/make-4.3.tar.gz
        tar xvzf make-4.3.tar.gz
        cd make-4.3
        ./configure
        bash ./build.sh
        sudo install ./make /usr/bin/make
        cd ..
        rm -rf make-4.3
        rm -rf make-4.3.tar.gz
    - name: build ct-ng
      run: |
        git clone --depth=1 https://github.com/crosstool-ng/crosstool-ng.git
        cd crosstool-ng
        ./bootstrap
        ./configure --prefix=$PWD/.local/
        make
        make install
        cd ..
        rm -rf crosstool-ng
        mkdir build
        cd build
        ct-ng aarch64-unknown-linux-gnu
        sed -i -e '/CT_LOG_PROGRESS_BAR/s/y$/n/' .config
        sed -i -e '/CT_LOCAL_TARBALLS_DIR/s/HOME/CT_TOP_DIR/' .config
        sed -i -e '/CT_PREFIX_DIR/s/HOME/CT_TOP_DIR/' .config
        ct-ng build
