on:
  push:
  pull_request:

jobs:
  test:
    name: Test on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - name: get latest build tools
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa -y
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -y gperf help2man libtool-bin gcc-11 g++-11
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100
        sudo update-alternatives --install /usr/bin/cpp cpp-bin /usr/bin/cpp-11 100
        make --version
        gcc --version
        g++ --version
